/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartRelationsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  excludedFolders: [],
  scoringWeights: {
    bm25: 0.4,
    jaccard: 0.2,
    termOverlap: 0.2,
    graphProximity: 0.2
  },
  minSimilarityThreshold: 0.1,
  maxRelatedNotes: 20,
  ngramSize: 3,
  useRichRelatedFormat: true,
  maxTokenizationLength: 5e4
};
var SmartRelationsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smart Relations Settings" });
    new import_obsidian.Setting(containerEl).setName("Excluded folders").setDesc("Comma-separated list of folders to exclude from indexing").addText((text) => text.setPlaceholder("templates, archive").setValue(this.plugin.settings.excludedFolders.join(", ")).onChange(async (value) => {
      this.plugin.settings.excludedFolders = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Rich related format").setDesc("Use object format {uuid, rel, auto} instead of simple UUID strings in related field").addToggle((toggle) => toggle.setValue(this.plugin.settings.useRichRelatedFormat).onChange(async (value) => {
      this.plugin.settings.useRichRelatedFormat = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Scoring Weights" });
    containerEl.createEl("p", { text: "Weights should sum to 1.0", cls: "setting-item-description" });
    const weightKeys = [
      { key: "bm25", name: "BM25 weight" },
      { key: "jaccard", name: "Jaccard (tag) weight" },
      { key: "termOverlap", name: "Term overlap weight" },
      { key: "graphProximity", name: "Graph proximity weight" }
    ];
    for (const { key, name } of weightKeys) {
      new import_obsidian.Setting(containerEl).setName(name).addSlider((slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.scoringWeights[key]).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.scoringWeights[key] = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("Minimum similarity threshold").setDesc("Results below this score will be filtered out").addSlider((slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.minSimilarityThreshold).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.minSimilarityThreshold = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Max related notes").setDesc("Maximum number of related notes to display").addSlider((slider) => slider.setLimits(5, 50, 5).setValue(this.plugin.settings.maxRelatedNotes).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxRelatedNotes = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("N-gram size").setDesc("Character n-gram size for fuzzy matching (2-5)").addSlider((slider) => slider.setLimits(2, 5, 1).setValue(this.plugin.settings.ngramSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.ngramSize = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/utils/uuid.ts
var UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
function isValidUuid(value) {
  return UUID_V4_REGEX.test(value.toLowerCase());
}

// src/utils/frontmatter.ts
function parseFrontmatter(cache) {
  const fm = cache.frontmatter;
  if (!fm) return null;
  const uuid = fm.uuid;
  if (!uuid || typeof uuid !== "string" || !isValidUuid(uuid)) {
    return null;
  }
  return {
    uuid: uuid.toLowerCase(),
    type: typeof fm.type === "string" ? fm.type : "note",
    status: typeof fm.status === "string" ? fm.status : "raw",
    created: typeof fm.created === "string" ? fm.created : "",
    modified: typeof fm.modified === "string" ? fm.modified : "",
    tags: extractFrontmatterTags(fm),
    related: parseRelatedField(fm.related),
    summary: typeof fm.summary === "string" ? fm.summary : ""
  };
}
function extractTags(cache) {
  const tagSet = /* @__PURE__ */ new Set();
  const fm = cache.frontmatter;
  if (fm && Array.isArray(fm.tags)) {
    for (const tag of fm.tags) {
      if (typeof tag === "string") {
        tagSet.add(normalizeTag(tag));
      }
    }
  }
  if (cache.tags) {
    for (const tagRef of cache.tags) {
      tagSet.add(normalizeTag(tagRef.tag));
    }
  }
  return Array.from(tagSet);
}
function normalizeTag(tag) {
  return tag.replace(/^#/, "").toLowerCase().trim();
}
function extractFrontmatterTags(fm) {
  if (!fm.tags) return [];
  if (Array.isArray(fm.tags)) {
    return fm.tags.filter((t) => typeof t === "string").map((t) => normalizeTag(t));
  }
  if (typeof fm.tags === "string") {
    return [normalizeTag(fm.tags)];
  }
  return [];
}
function parseRelatedField(related) {
  if (!related || !Array.isArray(related)) return [];
  return related.map((entry) => {
    if (typeof entry === "string") {
      if (isValidUuid(entry)) {
        return { uuid: entry.toLowerCase(), rel: "related", auto: false };
      }
      return null;
    }
    if (typeof entry === "object" && entry !== null) {
      const obj = entry;
      const uuid = typeof obj.uuid === "string" ? obj.uuid : "";
      if (!isValidUuid(uuid)) return null;
      return {
        uuid: uuid.toLowerCase(),
        rel: typeof obj.rel === "string" ? obj.rel : "related",
        auto: typeof obj.auto === "boolean" ? obj.auto : false
      };
    }
    return null;
  }).filter((e) => e !== null);
}

// src/indexer/UuidIndexer.ts
var UuidIndexer = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Build a complete UUID index from all markdown files.
   * Skips files without valid UUIDs. Warns on duplicates.
   * @param excludedFolders - folder paths to skip
   */
  async buildIndex(excludedFolders = []) {
    const index = {};
    const warnings = [];
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      if (this.isExcluded(file, excludedFolders)) continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!cache) continue;
      const result = this.indexSingleFile(file, cache);
      if (!result) {
        warnings.push(`No valid UUID in: ${file.path}`);
        continue;
      }
      const { uuid, entry } = result;
      if (index[uuid]) {
        warnings.push(
          `Duplicate UUID ${uuid} found in "${file.path}" and "${index[uuid].path}". Keeping first occurrence.`
        );
        continue;
      }
      index[uuid] = entry;
    }
    return { index, warnings };
  }
  /**
   * Index a single file. Returns null if no valid UUID.
   */
  indexSingleFile(file, cache) {
    var _a;
    const fm = parseFrontmatter(cache);
    if (!fm) return null;
    const tags = extractTags(cache);
    let title = file.basename;
    const firstHeading = (_a = cache.headings) == null ? void 0 : _a[0];
    if (firstHeading) {
      title = firstHeading.heading;
    }
    const entry = {
      path: file.path,
      title,
      type: fm.type,
      tags,
      relationCount: fm.related.length,
      lastModified: file.stat.mtime
    };
    return { uuid: fm.uuid, entry };
  }
  /**
   * Remove a UUID from the index.
   */
  removeFile(index, uuid) {
    delete index[uuid];
  }
  /**
   * Update a UUID entry in the index.
   */
  updateFile(index, uuid, entry) {
    index[uuid] = entry;
  }
  isExcluded(file, excludedFolders) {
    return excludedFolders.some((folder) => {
      const normalized = folder.endsWith("/") ? folder : folder + "/";
      return file.path.startsWith(normalized) || file.path.startsWith(folder);
    });
  }
};

// src/indexer/TermIndexer.ts
var import_obsidian2 = require("obsidian");

// src/nlp/stopwords.ts
var STOPWORDS = /* @__PURE__ */ new Set([
  "a",
  "about",
  "above",
  "after",
  "again",
  "against",
  "all",
  "am",
  "an",
  "and",
  "any",
  "are",
  "aren't",
  "as",
  "at",
  "be",
  "because",
  "been",
  "before",
  "being",
  "below",
  "between",
  "both",
  "but",
  "by",
  "can",
  "can't",
  "cannot",
  "could",
  "couldn't",
  "did",
  "didn't",
  "do",
  "does",
  "doesn't",
  "doing",
  "don't",
  "down",
  "during",
  "each",
  "few",
  "for",
  "from",
  "further",
  "get",
  "got",
  "had",
  "hadn't",
  "has",
  "hasn't",
  "have",
  "haven't",
  "having",
  "he",
  "he'd",
  "he'll",
  "he's",
  "her",
  "here",
  "here's",
  "hers",
  "herself",
  "him",
  "himself",
  "his",
  "how",
  "how's",
  "i",
  "i'd",
  "i'll",
  "i'm",
  "i've",
  "if",
  "in",
  "into",
  "is",
  "isn't",
  "it",
  "it's",
  "its",
  "itself",
  "just",
  "let",
  "let's",
  "me",
  "might",
  "more",
  "most",
  "mustn't",
  "my",
  "myself",
  "no",
  "nor",
  "not",
  "now",
  "of",
  "off",
  "on",
  "once",
  "only",
  "or",
  "other",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "over",
  "own",
  "quite",
  "s",
  "same",
  "say",
  "shan't",
  "she",
  "she'd",
  "she'll",
  "she's",
  "should",
  "shouldn't",
  "so",
  "some",
  "such",
  "t",
  "than",
  "that",
  "that's",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "there",
  "there's",
  "these",
  "they",
  "they'd",
  "they'll",
  "they're",
  "they've",
  "this",
  "those",
  "through",
  "to",
  "too",
  "under",
  "until",
  "up",
  "upon",
  "us",
  "use",
  "used",
  "using",
  "very",
  "was",
  "wasn't",
  "we",
  "we'd",
  "we'll",
  "we're",
  "we've",
  "were",
  "weren't",
  "what",
  "what's",
  "when",
  "when's",
  "where",
  "where's",
  "which",
  "while",
  "who",
  "who's",
  "whom",
  "why",
  "why's",
  "will",
  "with",
  "won't",
  "would",
  "wouldn't",
  "yet",
  "you",
  "you'd",
  "you'll",
  "you're",
  "you've",
  "your",
  "yours",
  "yourself",
  "yourselves"
]);

// src/nlp/stemmer.ts
function isConsonant(word, i) {
  const ch = word[i];
  if (ch === "a" || ch === "e" || ch === "i" || ch === "o" || ch === "u") {
    return false;
  }
  if (ch === "y") {
    if (i === 0) {
      return true;
    }
    return !isConsonant(word, i - 1);
  }
  return true;
}
function measure(word) {
  let m = 0;
  let i = 0;
  const len = word.length;
  if (len === 0) return 0;
  while (i < len && isConsonant(word, i)) {
    i++;
  }
  while (i < len) {
    while (i < len && !isConsonant(word, i)) {
      i++;
    }
    if (i >= len) break;
    while (i < len && isConsonant(word, i)) {
      i++;
    }
    m++;
  }
  return m;
}
function hasVowel(word) {
  for (let i = 0; i < word.length; i++) {
    if (!isConsonant(word, i)) {
      return true;
    }
  }
  return false;
}
function endsWithDoubleConsonant(word) {
  const len = word.length;
  if (len < 2) return false;
  if (word[len - 1] !== word[len - 2]) return false;
  return isConsonant(word, len - 1);
}
function endsCVC(word) {
  const len = word.length;
  if (len < 3) return false;
  if (!isConsonant(word, len - 1) || isConsonant(word, len - 2) || !isConsonant(word, len - 3)) {
    return false;
  }
  const ch = word[len - 1];
  if (ch === "w" || ch === "x" || ch === "y") {
    return false;
  }
  return true;
}
function step1a(word) {
  if (word.endsWith("sses")) {
    return word.slice(0, -2);
  }
  if (word.endsWith("ies")) {
    return word.slice(0, -2);
  }
  if (word.endsWith("ss")) {
    return word;
  }
  if (word.endsWith("s")) {
    return word.slice(0, -1);
  }
  return word;
}
function step1b(word) {
  if (word.endsWith("eed")) {
    const stem2 = word.slice(0, -3);
    if (measure(stem2) > 0) {
      return word.slice(0, -1);
    }
    return word;
  }
  let modified = false;
  let result = word;
  if (word.endsWith("ed")) {
    const stem2 = word.slice(0, -2);
    if (hasVowel(stem2)) {
      result = stem2;
      modified = true;
    }
  } else if (word.endsWith("ing")) {
    const stem2 = word.slice(0, -3);
    if (hasVowel(stem2)) {
      result = stem2;
      modified = true;
    }
  }
  if (modified) {
    if (result.endsWith("at") || result.endsWith("bl") || result.endsWith("iz")) {
      result = result + "e";
    } else if (endsWithDoubleConsonant(result)) {
      const last = result[result.length - 1];
      if (last !== "l" && last !== "s" && last !== "z") {
        result = result.slice(0, -1);
      }
    } else if (measure(result) === 1 && endsCVC(result)) {
      result = result + "e";
    }
  }
  return result;
}
function step1c(word) {
  if (word.endsWith("y")) {
    const stem2 = word.slice(0, -1);
    if (hasVowel(stem2)) {
      return stem2 + "i";
    }
  }
  return word;
}
function step2(word) {
  const suffixes = [
    ["ational", "ate"],
    ["tional", "tion"],
    ["enci", "ence"],
    ["anci", "ance"],
    ["izer", "ize"],
    ["abli", "able"],
    ["alli", "al"],
    ["entli", "ent"],
    ["eli", "e"],
    ["ousli", "ous"],
    ["ization", "ize"],
    ["ation", "ate"],
    ["ator", "ate"],
    ["alism", "al"],
    ["iveness", "ive"],
    ["fulness", "ful"],
    ["ousness", "ous"],
    ["aliti", "al"],
    ["iviti", "ive"],
    ["biliti", "ble"],
    ["logi", "log"]
  ];
  for (const [suffix, replacement] of suffixes) {
    if (word.endsWith(suffix)) {
      const stem2 = word.slice(0, -suffix.length);
      if (measure(stem2) > 0) {
        return stem2 + replacement;
      }
      return word;
    }
  }
  return word;
}
function step3(word) {
  const suffixes = [
    ["icate", "ic"],
    ["ative", ""],
    ["alize", "al"],
    ["iciti", "ic"],
    ["ical", "ic"],
    ["ful", ""],
    ["ness", ""]
  ];
  for (const [suffix, replacement] of suffixes) {
    if (word.endsWith(suffix)) {
      const stem2 = word.slice(0, -suffix.length);
      if (measure(stem2) > 0) {
        return stem2 + replacement;
      }
      return word;
    }
  }
  return word;
}
function step4(word) {
  const suffixes = [
    "al",
    "ance",
    "ence",
    "er",
    "ic",
    "able",
    "ible",
    "ant",
    "ement",
    "ment",
    "ent",
    "ou",
    "ism",
    "ate",
    "iti",
    "ous",
    "ive",
    "ize"
  ];
  if (word.endsWith("ion")) {
    const stem2 = word.slice(0, -3);
    if (measure(stem2) > 1 && stem2.length > 0 && (stem2.endsWith("s") || stem2.endsWith("t"))) {
      return stem2;
    }
  }
  for (const suffix of suffixes) {
    if (word.endsWith(suffix)) {
      const stem2 = word.slice(0, -suffix.length);
      if (measure(stem2) > 1) {
        return stem2;
      }
      return word;
    }
  }
  return word;
}
function step5a(word) {
  if (word.endsWith("e")) {
    const stem2 = word.slice(0, -1);
    if (measure(stem2) > 1) {
      return stem2;
    }
    if (measure(stem2) === 1 && !endsCVC(stem2)) {
      return stem2;
    }
  }
  return word;
}
function step5b(word) {
  if (word.endsWith("ll") && measure(word.slice(0, -1)) > 1) {
    return word.slice(0, -1);
  }
  return word;
}
function stem(word) {
  word = word.toLowerCase();
  if (word.length < 3) {
    return word;
  }
  word = step1a(word);
  word = step1b(word);
  word = step1c(word);
  word = step2(word);
  word = step3(word);
  word = step4(word);
  word = step5a(word);
  word = step5b(word);
  return word;
}

// src/nlp/tokenizer.ts
function extractBodyText(content) {
  if (!content.startsWith("---")) {
    return content;
  }
  const closingIndex = content.indexOf("\n---", 3);
  if (closingIndex === -1) {
    return content;
  }
  const afterFrontmatter = closingIndex + 4;
  if (afterFrontmatter >= content.length) {
    return "";
  }
  const rest = content.slice(afterFrontmatter);
  if (rest.startsWith("\n")) {
    return rest.slice(1);
  }
  if (rest.startsWith("\r\n")) {
    return rest.slice(2);
  }
  return rest;
}
function stripMarkdown(text) {
  let result = text;
  result = result.replace(/```[\s\S]*?```/g, " ");
  result = result.replace(/`[^`\n]+`/g, " ");
  result = result.replace(/<[^>]+>/g, " ");
  result = result.replace(/!\[([^\]]*)\]\([^)]*\)/g, " ");
  result = result.replace(/!\[\[[^\]]*\]\]/g, " ");
  result = result.replace(/\[\[([^\]|]*)\|([^\]]*)\]\]/g, "$2");
  result = result.replace(/\[\[([^\]]*)\]\]/g, "$1");
  result = result.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  result = result.replace(/^#{1,6}\s+/gm, "");
  result = result.replace(/\*\*\*([^*]+)\*\*\*/g, "$1");
  result = result.replace(/\*\*([^*]+)\*\*/g, "$1");
  result = result.replace(/\*([^*]+)\*/g, "$1");
  result = result.replace(/___([^_]+)___/g, "$1");
  result = result.replace(/__([^_]+)__/g, "$1");
  result = result.replace(/_([^_]+)_/g, "$1");
  result = result.replace(/^[-*_]{3,}\s*$/gm, " ");
  result = result.replace(/^>\s*/gm, "");
  result = result.replace(/^[\t ]*[-*+]\s+/gm, "");
  result = result.replace(/^[\t ]*\d+\.\s+/gm, "");
  result = result.replace(/~~([^~]+)~~/g, "$1");
  result = result.replace(/==([^=]+)==/g, "$1");
  result = result.replace(/\s+/g, " ");
  return result.trim();
}
function tokenize(text) {
  const stripped = stripMarkdown(text);
  const words = stripped.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length >= 2);
  return words.filter((w) => !STOPWORDS.has(w)).map((w) => stem(w));
}
function tokenizeWithPositions(text) {
  const results = [];
  const wordRegex = /[a-zA-Z0-9]+/g;
  let match;
  while ((match = wordRegex.exec(text)) !== null) {
    const raw = match[0].toLowerCase();
    if (raw.length < 2) {
      continue;
    }
    if (STOPWORDS.has(raw)) {
      continue;
    }
    const stemmed = stem(raw);
    results.push({
      term: stemmed,
      position: match.index
    });
  }
  return results;
}

// src/indexer/TermIndexer.ts
var TermIndexer = class {
  constructor(app, maxTokenizationLength = 5e4) {
    this.app = app;
    this.maxTokenizationLength = maxTokenizationLength;
  }
  /**
   * Build the complete term index from all files.
   * Only indexes files that have a UUID in the UuidIndex.
   */
  async buildIndex(uuidIndex) {
    const termIndex = {};
    let totalWordCount = 0;
    let totalDocs = 0;
    const allTerms = /* @__PURE__ */ new Set();
    for (const [uuid, entry] of Object.entries(uuidIndex)) {
      const file = this.app.vault.getAbstractFileByPath(entry.path);
      if (!file || !(file instanceof import_obsidian2.TFile)) continue;
      const content = await this.app.vault.cachedRead(file);
      const body = extractBodyText(content);
      const truncated = body.length > this.maxTokenizationLength ? body.slice(0, this.maxTokenizationLength) : body;
      const tokens = tokenizeWithPositions(truncated);
      const termFreqs = /* @__PURE__ */ new Map();
      for (const { term, position } of tokens) {
        const existing = termFreqs.get(term);
        if (existing) {
          existing.count++;
          existing.positions.push(position);
        } else {
          termFreqs.set(term, { count: 1, positions: [position] });
        }
      }
      for (const [term, { count, positions }] of termFreqs) {
        allTerms.add(term);
        let postings = termIndex[term];
        if (!postings) {
          postings = [];
          termIndex[term] = postings;
        }
        postings.push({
          uuid,
          tf: count,
          positions
        });
      }
      totalWordCount += tokens.length;
      totalDocs++;
    }
    const corpusStats = {
      totalDocuments: totalDocs,
      avgDocumentLength: totalDocs > 0 ? totalWordCount / totalDocs : 0,
      totalTerms: allTerms.size
    };
    return { termIndex, corpusStats };
  }
  /**
   * Index a single document. Returns its postings and word count.
   */
  indexSingleDocument(uuid, content) {
    const body = extractBodyText(content);
    const truncated = body.length > this.maxTokenizationLength ? body.slice(0, this.maxTokenizationLength) : body;
    const tokens = tokenizeWithPositions(truncated);
    const postings = /* @__PURE__ */ new Map();
    const termFreqs = /* @__PURE__ */ new Map();
    for (const { term, position } of tokens) {
      const existing = termFreqs.get(term);
      if (existing) {
        existing.count++;
        existing.positions.push(position);
      } else {
        termFreqs.set(term, { count: 1, positions: [position] });
      }
    }
    for (const [term, { count, positions }] of termFreqs) {
      postings.set(term, { uuid, tf: count, positions });
    }
    return { postings, wordCount: tokens.length };
  }
  /**
   * Compute IDF for a term using the BM25 variant.
   * IDF(t) = log((N - n(t) + 0.5) / (n(t) + 0.5) + 1)
   */
  computeIdf(term, termIndex, totalDocs) {
    const postings = termIndex[term];
    const df = postings ? postings.length : 0;
    return Math.log((totalDocs - df + 0.5) / (df + 0.5) + 1);
  }
  /**
   * Remove all postings for a given UUID from the term index.
   */
  removeDocument(termIndex, uuid) {
    for (const term of Object.keys(termIndex)) {
      const postings = termIndex[term];
      if (!postings) continue;
      const filtered = postings.filter((p) => p.uuid !== uuid);
      if (filtered.length === 0) {
        delete termIndex[term];
      } else {
        termIndex[term] = filtered;
      }
    }
  }
};

// src/indexer/TagIndexer.ts
var TagIndexer = class {
  /**
   * Build the tag co-occurrence matrix from the UUID index.
   * For each document, every pair of its tags increments the co-occurrence count.
   * The matrix is symmetric: cooccurrence[A][B] === cooccurrence[B][A].
   */
  buildIndex(uuidIndex) {
    const cooccurrence = {};
    for (const entry of Object.values(uuidIndex)) {
      const tags = entry.tags;
      if (tags.length < 2) continue;
      for (let i = 0; i < tags.length; i++) {
        for (let j = i + 1; j < tags.length; j++) {
          const tagA = tags[i];
          const tagB = tags[j];
          this.incrementCooccurrence(cooccurrence, tagA, tagB);
          this.incrementCooccurrence(cooccurrence, tagB, tagA);
        }
      }
    }
    return cooccurrence;
  }
  /**
   * Get the set of tags for a specific UUID.
   */
  getTagsForUuid(uuid, uuidIndex) {
    const entry = uuidIndex[uuid];
    return entry ? entry.tags : [];
  }
  /**
   * Get all tags that co-occur with a given tag, sorted by count descending.
   */
  getRelatedTags(tag, cooccurrence) {
    const entry = cooccurrence[tag];
    if (!entry) return [];
    return Object.entries(entry).map(([t, count]) => ({ tag: t, count })).sort((a, b) => b.count - a.count);
  }
  incrementCooccurrence(cooccurrence, tagA, tagB) {
    var _a;
    let tagAEntry = cooccurrence[tagA];
    if (!tagAEntry) {
      tagAEntry = {};
      cooccurrence[tagA] = tagAEntry;
    }
    tagAEntry[tagB] = ((_a = tagAEntry[tagB]) != null ? _a : 0) + 1;
  }
};

// src/indexer/NgramIndexer.ts
var NgramIndexer = class {
  constructor(ngramSize = 3) {
    this.ngramSize = ngramSize;
  }
  /**
   * Build the n-gram index from documents.
   * @param documents - Map of uuid -> text content (title + summary, first 500 chars)
   */
  buildIndex(documents) {
    const ngramIndex = {};
    for (const [uuid, text] of documents) {
      const ngrams = this.extractNgrams(text, this.ngramSize);
      const uniqueNgrams = new Set(ngrams);
      for (const ngram of uniqueNgrams) {
        let uuids = ngramIndex[ngram];
        if (!uuids) {
          uuids = [];
          ngramIndex[ngram] = uuids;
        }
        uuids.push(uuid);
      }
    }
    return ngramIndex;
  }
  /**
   * Extract character-level n-grams from text.
   */
  extractNgrams(text, n) {
    const normalized = text.toLowerCase().replace(/\s+/g, " ").trim();
    if (normalized.length < n) return [];
    const ngrams = [];
    for (let i = 0; i <= normalized.length - n; i++) {
      ngrams.push(normalized.slice(i, i + n));
    }
    return ngrams;
  }
  /**
   * Find documents similar to a query string using n-gram overlap.
   * Returns UUIDs sorted by overlap count descending.
   */
  findSimilar(query, ngramIndex, threshold = 0.1) {
    const queryNgrams = new Set(this.extractNgrams(query, this.ngramSize));
    if (queryNgrams.size === 0) return [];
    const uuidCounts = /* @__PURE__ */ new Map();
    for (const ngram of queryNgrams) {
      const uuids = ngramIndex[ngram];
      if (!uuids) continue;
      for (const uuid of uuids) {
        uuidCounts.set(uuid, (uuidCounts.get(uuid) || 0) + 1);
      }
    }
    const results = [];
    for (const [uuid, count] of uuidCounts) {
      const ratio = count / queryNgrams.size;
      if (ratio >= threshold) {
        results.push({ uuid, overlapCount: count, overlapRatio: ratio });
      }
    }
    return results.sort((a, b) => b.overlapCount - a.overlapCount);
  }
  /**
   * Remove all n-gram entries for a given UUID.
   */
  removeDocument(ngramIndex, uuid) {
    for (const ngram of Object.keys(ngramIndex)) {
      const uuids = ngramIndex[ngram];
      if (!uuids) continue;
      const filtered = uuids.filter((id) => id !== uuid);
      if (filtered.length === 0) {
        delete ngramIndex[ngram];
      } else {
        ngramIndex[ngram] = filtered;
      }
    }
  }
};

// src/indexer/RelationGraphBuilder.ts
var import_obsidian3 = require("obsidian");
var RelationGraphBuilder = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Build the relation graph from all files' frontmatter.
   * Creates bidirectional edges for each related entry.
   * Validates that target UUIDs exist in the UUID index.
   */
  buildGraph(uuidIndex) {
    const graph = {};
    const warnings = [];
    for (const [sourceUuid, entry] of Object.entries(uuidIndex)) {
      const file = this.app.vault.getAbstractFileByPath(entry.path);
      if (!file || !(file instanceof import_obsidian3.TFile)) continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!cache) continue;
      const fm = parseFrontmatter(cache);
      if (!fm) continue;
      for (const rel of fm.related) {
        if (!uuidIndex[rel.uuid]) {
          warnings.push(
            `Dangling reference: "${entry.path}" references UUID ${rel.uuid} which does not exist in the index`
          );
          continue;
        }
        this.addEdge(graph, sourceUuid, rel.uuid, rel.rel, 1);
        this.addEdge(graph, rel.uuid, sourceUuid, rel.rel, 1);
      }
    }
    return { graph, warnings };
  }
  /**
   * Add an edge to the graph. Avoids duplicates.
   */
  addEdge(graph, source, target, type, weight = 1) {
    let edges = graph[source];
    if (!edges) {
      edges = [];
      graph[source] = edges;
    }
    const existing = edges.find((e) => e.target === target && e.type === type);
    if (existing) {
      existing.weight = Math.max(existing.weight, weight);
      return;
    }
    edges.push({ target, type, weight });
  }
  /**
   * Get all neighbors within `depth` hops using BFS.
   * Returns a Map of UUID -> distance (excluding the source).
   */
  getNeighbors(graph, uuid, depth = 2) {
    var _a;
    const distances = /* @__PURE__ */ new Map();
    const queue = [{ uuid, dist: 0 }];
    const visited = /* @__PURE__ */ new Set();
    visited.add(uuid);
    while (queue.length > 0) {
      const current = queue.shift();
      if (current.dist >= depth) continue;
      const edges = (_a = graph[current.uuid]) != null ? _a : [];
      for (const edge of edges) {
        if (!visited.has(edge.target)) {
          visited.add(edge.target);
          const newDist = current.dist + 1;
          distances.set(edge.target, newDist);
          queue.push({ uuid: edge.target, dist: newDist });
        }
      }
    }
    return distances;
  }
  /**
   * Find shortest path between two UUIDs using BFS.
   * Returns the path as an array of UUIDs, or empty array if no path exists.
   */
  findPath(graph, from, to, maxDepth = 5) {
    var _a;
    if (from === to) return [from];
    const queue = [{ uuid: from, path: [from] }];
    const visited = /* @__PURE__ */ new Set();
    visited.add(from);
    while (queue.length > 0) {
      const current = queue.shift();
      if (current.path.length > maxDepth) continue;
      const edges = (_a = graph[current.uuid]) != null ? _a : [];
      for (const edge of edges) {
        if (edge.target === to) {
          return [...current.path, to];
        }
        if (!visited.has(edge.target)) {
          visited.add(edge.target);
          queue.push({ uuid: edge.target, path: [...current.path, edge.target] });
        }
      }
    }
    return [];
  }
  /**
   * Remove all edges involving a UUID (both as source and target).
   */
  removeNode(graph, uuid) {
    delete graph[uuid];
    for (const sourceUuid of Object.keys(graph)) {
      const edges = graph[sourceUuid];
      if (!edges) continue;
      const filtered = edges.filter((e) => e.target !== uuid);
      if (filtered.length === 0) {
        delete graph[sourceUuid];
      } else {
        graph[sourceUuid] = filtered;
      }
    }
  }
};

// src/indexer/DocumentStats.ts
var DocumentStatsBuilder = class {
  /**
   * Compute stats for a single document given its term postings and word count.
   */
  computeStats(uuid, termPostings, wordCount, lastModified, idfLookup) {
    const uniqueTerms = termPostings.size;
    const avgTermFrequency = uniqueTerms > 0 ? wordCount / uniqueTerms : 0;
    let sumSquared = 0;
    for (const [term, { tf }] of termPostings) {
      const idf = idfLookup(term);
      const tfidf = tf * idf;
      sumSquared += tfidf * tfidf;
    }
    const vectorNorm = Math.sqrt(sumSquared);
    return {
      wordCount: Math.max(wordCount, 1),
      // Guard against division by zero in BM25
      uniqueTerms,
      avgTermFrequency,
      vectorNorm,
      lastModified
    };
  }
  /**
   * Build document stats for all documents using the term index.
   */
  buildAllStats(termIndex, corpusStats, lastModifiedLookup) {
    var _a, _b;
    const stats = {};
    const docTerms = /* @__PURE__ */ new Map();
    const docWordCounts = /* @__PURE__ */ new Map();
    for (const [term, postings] of Object.entries(termIndex)) {
      if (!postings) continue;
      for (const posting of postings) {
        let termMap = docTerms.get(posting.uuid);
        if (!termMap) {
          termMap = /* @__PURE__ */ new Map();
          docTerms.set(posting.uuid, termMap);
          docWordCounts.set(posting.uuid, 0);
        }
        termMap.set(term, posting.tf);
        docWordCounts.set(
          posting.uuid,
          ((_a = docWordCounts.get(posting.uuid)) != null ? _a : 0) + posting.tf
        );
      }
    }
    const idfLookup = (term) => {
      const postings = termIndex[term];
      const df = postings ? postings.length : 0;
      return Math.log(
        (corpusStats.totalDocuments - df + 0.5) / (df + 0.5) + 1
      );
    };
    for (const [uuid, terms] of docTerms) {
      const wordCount = (_b = docWordCounts.get(uuid)) != null ? _b : 0;
      const termPostings = /* @__PURE__ */ new Map();
      for (const [term, tf] of terms) {
        termPostings.set(term, { tf });
      }
      stats[uuid] = this.computeStats(
        uuid,
        termPostings,
        wordCount,
        lastModifiedLookup(uuid),
        idfLookup
      );
    }
    return stats;
  }
};

// src/indexer/IndexManager.ts
var INDEX_FILES = {
  uuid: "_uuid_index.json",
  term: "_term_index.json",
  tag: "_tag_cooccurrence.json",
  ngram: "_ngram_index.json",
  graph: "_relation_graph.json",
  docStats: "_document_stats.json",
  corpusStats: "_corpus_stats.json"
};
var IndexManager = class {
  constructor(app, settings, cache) {
    this.app = app;
    this.settings = settings;
    this.cache = cache;
    // Index data
    this.uuidIndex = {};
    this.termIndex = {};
    this.tagCooccurrence = {};
    this.ngramIndex = {};
    this.relationGraph = {};
    this.documentStats = {};
    this.corpusStats = { totalDocuments: 0, avgDocumentLength: 0, totalTerms: 0 };
    // Debounce
    this.pendingChanges = /* @__PURE__ */ new Map();
    this.debounceTimer = null;
    this.DEBOUNCE_MS = 500;
    // State
    this.isIndexing = false;
    this.lastIndexTime = null;
    this.indexLoaded = false;
    this.uuidIndexer = new UuidIndexer(app);
    this.termIndexer = new TermIndexer(app, settings.maxTokenizationLength);
    this.tagIndexer = new TagIndexer();
    this.ngramIndexer = new NgramIndexer(settings.ngramSize);
    this.graphBuilder = new RelationGraphBuilder(app);
    this.statsBuilder = new DocumentStatsBuilder();
  }
  // ==================== Full Rebuild ====================
  /**
   * Rebuild all indexes from scratch.
   * Processes files in batches to avoid freezing the UI.
   */
  async rebuildAll(onProgress) {
    if (this.isIndexing) {
      console.warn("Smart Relations: Already indexing, skipping rebuild");
      return;
    }
    this.isIndexing = true;
    const startTime = Date.now();
    try {
      onProgress == null ? void 0 : onProgress("Starting full reindex...", 0);
      onProgress == null ? void 0 : onProgress("Building UUID index...", 0.1);
      const { index: uuidIndex, warnings: uuidWarnings } = await this.uuidIndexer.buildIndex(this.settings.excludedFolders);
      this.uuidIndex = uuidIndex;
      for (const w of uuidWarnings) console.warn(`Smart Relations: ${w}`);
      const totalFiles = Object.keys(uuidIndex).length;
      onProgress == null ? void 0 : onProgress(`UUID index: ${totalFiles} notes indexed`, 0.2);
      onProgress == null ? void 0 : onProgress("Building term index...", 0.3);
      const { termIndex, corpusStats } = await this.termIndexer.buildIndex(uuidIndex);
      this.termIndex = termIndex;
      this.corpusStats = corpusStats;
      onProgress == null ? void 0 : onProgress(`Term index: ${Object.keys(termIndex).length} unique terms`, 0.5);
      onProgress == null ? void 0 : onProgress("Building tag co-occurrence...", 0.6);
      this.tagCooccurrence = this.tagIndexer.buildIndex(uuidIndex);
      onProgress == null ? void 0 : onProgress("Building n-gram index...", 0.7);
      const ngramDocuments = /* @__PURE__ */ new Map();
      for (const [uuid, entry] of Object.entries(uuidIndex)) {
        ngramDocuments.set(uuid, `${entry.title} ${entry.path}`);
      }
      this.ngramIndex = this.ngramIndexer.buildIndex(ngramDocuments);
      onProgress == null ? void 0 : onProgress("Building relation graph...", 0.8);
      const { graph, warnings: graphWarnings } = this.graphBuilder.buildGraph(uuidIndex);
      this.relationGraph = graph;
      for (const w of graphWarnings) console.warn(`Smart Relations: ${w}`);
      onProgress == null ? void 0 : onProgress("Computing document statistics...", 0.9);
      this.documentStats = this.statsBuilder.buildAllStats(
        termIndex,
        corpusStats,
        (uuid) => {
          var _a, _b;
          return (_b = (_a = uuidIndex[uuid]) == null ? void 0 : _a.lastModified) != null ? _b : Date.now();
        }
      );
      await this.saveAllIndexes();
      this.lastIndexTime = Date.now();
      this.indexLoaded = true;
      const elapsed = ((Date.now() - startTime) / 1e3).toFixed(1);
      onProgress == null ? void 0 : onProgress(`Indexing complete: ${totalFiles} notes in ${elapsed}s`, 1);
      console.log(`Smart Relations: Full reindex completed \u2014 ${totalFiles} notes, ${Object.keys(termIndex).length} terms in ${elapsed}s`);
    } catch (e) {
      console.error("Smart Relations: Reindex failed:", e);
      onProgress == null ? void 0 : onProgress("Indexing failed \u2014 check console for details", 0);
    } finally {
      this.isIndexing = false;
    }
  }
  // ==================== Incremental Updates ====================
  /**
   * Handle a file change event. Debounces rapid changes.
   */
  handleFileChange(file, changeType) {
    if (!this.indexLoaded) return;
    if (file.extension !== "md") return;
    if (this.settings.excludedFolders.some((f) => file.path.startsWith(f))) return;
    this.pendingChanges.set(file.path, { file, type: changeType });
    this.scheduleFlush();
  }
  /**
   * Handle a file rename. Updates the path in UUID index.
   */
  handleFileRename(file, oldPath) {
    if (!this.indexLoaded) return;
    if (file.extension !== "md") return;
    this.pendingChanges.set(file.path, { file, type: "modify" });
    if (!this.isIndexing) {
      for (const [, entry] of Object.entries(this.uuidIndex)) {
        if (entry.path === oldPath) {
          entry.path = file.path;
          entry.title = file.basename;
          break;
        }
      }
    }
    this.scheduleFlush();
  }
  scheduleFlush() {
    if (this.debounceTimer !== null) {
      window.clearTimeout(this.debounceTimer);
    }
    this.debounceTimer = window.setTimeout(() => {
      void this.flushPendingChanges();
    }, this.DEBOUNCE_MS);
  }
  async flushPendingChanges() {
    if (this.pendingChanges.size === 0) return;
    if (this.isIndexing) {
      this.scheduleFlush();
      return;
    }
    const changes = new Map(this.pendingChanges);
    this.pendingChanges.clear();
    this.debounceTimer = null;
    this.isIndexing = true;
    try {
      for (const [path, { file, type }] of changes) {
        switch (type) {
          case "delete":
            this.handleDelete(path);
            break;
          case "create":
          case "modify":
            await this.handleCreateOrModify(file);
            break;
        }
      }
      this.tagCooccurrence = this.tagIndexer.buildIndex(this.uuidIndex);
      this.documentStats = this.statsBuilder.buildAllStats(
        this.termIndex,
        this.corpusStats,
        (uuid) => {
          var _a, _b;
          return (_b = (_a = this.uuidIndex[uuid]) == null ? void 0 : _a.lastModified) != null ? _b : Date.now();
        }
      );
      let totalWords = 0;
      const allTerms = /* @__PURE__ */ new Set();
      for (const [term, postings] of Object.entries(this.termIndex)) {
        allTerms.add(term);
        if (postings) {
          for (const p of postings) {
            totalWords += p.tf;
          }
        }
      }
      const totalDocs = Object.keys(this.uuidIndex).length;
      this.corpusStats = {
        totalDocuments: totalDocs,
        avgDocumentLength: totalDocs > 0 ? totalWords / totalDocs : 0,
        totalTerms: allTerms.size
      };
      await this.saveAllIndexes();
      this.lastIndexTime = Date.now();
    } catch (e) {
      console.error("Smart Relations: Incremental update failed:", e);
    } finally {
      this.isIndexing = false;
    }
  }
  handleDelete(path) {
    let deletedUuid = null;
    for (const [uuid, entry] of Object.entries(this.uuidIndex)) {
      if (entry.path === path) {
        deletedUuid = uuid;
        break;
      }
    }
    if (!deletedUuid) return;
    this.uuidIndexer.removeFile(this.uuidIndex, deletedUuid);
    this.termIndexer.removeDocument(this.termIndex, deletedUuid);
    this.ngramIndexer.removeDocument(this.ngramIndex, deletedUuid);
    this.graphBuilder.removeNode(this.relationGraph, deletedUuid);
    delete this.documentStats[deletedUuid];
    console.log(`Smart Relations: Removed deleted file from index (UUID: ${deletedUuid})`);
  }
  async handleCreateOrModify(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache) return;
    const result = this.uuidIndexer.indexSingleFile(file, cache);
    if (!result) return;
    const { uuid, entry } = result;
    if (this.uuidIndex[uuid]) {
      this.termIndexer.removeDocument(this.termIndex, uuid);
      this.ngramIndexer.removeDocument(this.ngramIndex, uuid);
      this.graphBuilder.removeNode(this.relationGraph, uuid);
      delete this.documentStats[uuid];
    }
    this.uuidIndexer.updateFile(this.uuidIndex, uuid, entry);
    const content = await this.app.vault.cachedRead(file);
    const { postings } = this.termIndexer.indexSingleDocument(uuid, content);
    for (const [term, posting] of postings) {
      const existing = this.termIndex[term];
      if (!existing) {
        this.termIndex[term] = [];
      }
      this.termIndex[term].push(posting);
    }
    const ngramText = `${entry.title} ${entry.path}`;
    const ngramDocs = /* @__PURE__ */ new Map();
    ngramDocs.set(uuid, ngramText);
    const newNgrams = this.ngramIndexer.buildIndex(ngramDocs);
    for (const [ngram, uuids] of Object.entries(newNgrams)) {
      if (!uuids) continue;
      const existingNgram = this.ngramIndex[ngram];
      if (!existingNgram) {
        this.ngramIndex[ngram] = [];
      }
      this.ngramIndex[ngram].push(...uuids);
    }
    const fm = parseFrontmatter(cache);
    if (fm) {
      for (const rel of fm.related) {
        if (this.uuidIndex[rel.uuid]) {
          this.graphBuilder.addEdge(this.relationGraph, uuid, rel.uuid, rel.rel, 1);
          this.graphBuilder.addEdge(this.relationGraph, rel.uuid, uuid, rel.rel, 1);
        }
      }
    }
    console.log(`Smart Relations: Updated index for "${file.path}" (UUID: ${uuid})`);
  }
  // ==================== Persistence ====================
  async loadAllIndexes() {
    try {
      const [uuid, term, tag, ngram, graph, docStats, corpus] = await Promise.all([
        this.cache.loadIndex(INDEX_FILES.uuid),
        this.cache.loadIndex(INDEX_FILES.term),
        this.cache.loadIndex(INDEX_FILES.tag),
        this.cache.loadIndex(INDEX_FILES.ngram),
        this.cache.loadIndex(INDEX_FILES.graph),
        this.cache.loadIndex(INDEX_FILES.docStats),
        this.cache.loadIndex(INDEX_FILES.corpusStats)
      ]);
      if (uuid && term) {
        this.uuidIndex = uuid;
        this.termIndex = term;
        this.tagCooccurrence = tag != null ? tag : {};
        this.ngramIndex = ngram != null ? ngram : {};
        this.relationGraph = graph != null ? graph : {};
        this.documentStats = docStats != null ? docStats : {};
        this.corpusStats = corpus != null ? corpus : { totalDocuments: 0, avgDocumentLength: 0, totalTerms: 0 };
        this.indexLoaded = true;
        this.lastIndexTime = Date.now();
        console.log(`Smart Relations: Loaded indexes from disk (${Object.keys(this.uuidIndex).length} notes)`);
        return true;
      }
      return false;
    } catch (e) {
      console.warn("Smart Relations: Failed to load indexes from disk:", e);
      return false;
    }
  }
  async saveAllIndexes() {
    await Promise.all([
      this.cache.saveIndex(INDEX_FILES.uuid, this.uuidIndex),
      this.cache.saveIndex(INDEX_FILES.term, this.termIndex),
      this.cache.saveIndex(INDEX_FILES.tag, this.tagCooccurrence),
      this.cache.saveIndex(INDEX_FILES.ngram, this.ngramIndex),
      this.cache.saveIndex(INDEX_FILES.graph, this.relationGraph),
      this.cache.saveIndex(INDEX_FILES.docStats, this.documentStats),
      this.cache.saveIndex(INDEX_FILES.corpusStats, this.corpusStats)
    ]);
  }
  // ==================== Accessors ====================
  getUuidIndex() {
    return this.uuidIndex;
  }
  getTermIndex() {
    return this.termIndex;
  }
  getTagCooccurrence() {
    return this.tagCooccurrence;
  }
  getNgramIndex() {
    return this.ngramIndex;
  }
  getRelationGraph() {
    return this.relationGraph;
  }
  getDocumentStats() {
    return this.documentStats;
  }
  getCorpusStats() {
    return this.corpusStats;
  }
  getUuidForFile(file) {
    for (const [uuid, entry] of Object.entries(this.uuidIndex)) {
      if (entry.path === file.path) return uuid;
    }
    return null;
  }
  isLoaded() {
    return this.indexLoaded;
  }
  isCurrentlyIndexing() {
    return this.isIndexing;
  }
  getLastIndexTime() {
    return this.lastIndexTime;
  }
  getNoteCount() {
    return Object.keys(this.uuidIndex).length;
  }
  /**
   * Get dirty files (modified since last index).
   */
  getDirtyFiles() {
    const files = this.app.vault.getMarkdownFiles();
    return files.filter((file) => {
      const uuid = this.getUuidForFile(file);
      if (!uuid) return true;
      const entry = this.uuidIndex[uuid];
      if (!entry) return true;
      return file.stat.mtime > entry.lastModified;
    });
  }
};

// src/utils/cache.ts
var IndexCache = class {
  constructor(plugin) {
    this.plugin = plugin;
    var _a;
    this.basePath = `${(_a = plugin.manifest.dir) != null ? _a : ".obsidian/plugins/smart-relations"}`;
  }
  /**
   * Load an index from a JSON file in the plugin data directory.
   * Returns null if file doesn't exist or parsing fails.
   */
  async loadIndex(filename) {
    const path = `${this.basePath}/${filename}`;
    try {
      const exists = await this.plugin.app.vault.adapter.exists(path);
      if (!exists) return null;
      const raw = await this.plugin.app.vault.adapter.read(path);
      return JSON.parse(raw);
    } catch (e) {
      console.warn(`Smart Relations: Failed to load index ${filename}:`, e);
      return null;
    }
  }
  /**
   * Save an index as a JSON file in the plugin data directory.
   * Creates the directory if it doesn't exist.
   */
  async saveIndex(filename, data) {
    const path = `${this.basePath}/${filename}`;
    try {
      const dirExists = await this.plugin.app.vault.adapter.exists(this.basePath);
      if (!dirExists) {
        await this.plugin.app.vault.adapter.mkdir(this.basePath);
      }
      const json = JSON.stringify(data);
      await this.plugin.app.vault.adapter.write(path, json);
    } catch (e) {
      console.error(`Smart Relations: Failed to save index ${filename}:`, e);
    }
  }
  /**
   * Check if an index file exists.
   */
  async exists(filename) {
    const path = `${this.basePath}/${filename}`;
    return this.plugin.app.vault.adapter.exists(path);
  }
};

// src/scoring/CombinedScorer.ts
var import_obsidian4 = require("obsidian");

// src/scoring/BM25Scorer.ts
var BM25Scorer = class {
  // document length normalization
  constructor(termIndex, documentStats, corpusStats) {
    this.termIndex = termIndex;
    this.documentStats = documentStats;
    this.corpusStats = corpusStats;
    this.k1 = 1.5;
    // term frequency saturation
    this.b = 0.75;
  }
  /**
   * Score all documents against a set of query terms.
   * Only scores documents that contain at least one query term.
   * Returns a map of uuid -> BM25 score.
   */
  score(queryTerms) {
    var _a;
    const scores = /* @__PURE__ */ new Map();
    const avgdl = this.corpusStats.avgDocumentLength || 1;
    for (const term of queryTerms) {
      const postings = this.termIndex[term];
      if (!postings) continue;
      const idf = this.computeIdf(postings.length);
      for (const posting of postings) {
        const docStat = this.documentStats[posting.uuid];
        const dl = docStat ? docStat.wordCount : avgdl;
        const termScore = this.computeTermScore(posting.tf, idf, dl, avgdl);
        scores.set(posting.uuid, ((_a = scores.get(posting.uuid)) != null ? _a : 0) + termScore);
      }
    }
    return scores;
  }
  /**
   * Score a specific document against query terms.
   */
  scoreDocument(queryTerms, uuid) {
    let total = 0;
    const avgdl = this.corpusStats.avgDocumentLength || 1;
    const docStat = this.documentStats[uuid];
    const dl = docStat ? docStat.wordCount : avgdl;
    for (const term of queryTerms) {
      const postings = this.termIndex[term];
      if (!postings) continue;
      const posting = postings.find((p) => p.uuid === uuid);
      if (!posting) continue;
      const idf = this.computeIdf(postings.length);
      total += this.computeTermScore(posting.tf, idf, dl, avgdl);
    }
    return total;
  }
  /**
   * IDF using the BM25 variant that avoids negative values.
   * IDF(t) = log((N - n(t) + 0.5) / (n(t) + 0.5) + 1)
   */
  computeIdf(df) {
    const N = this.corpusStats.totalDocuments || 1;
    return Math.log((N - df + 0.5) / (df + 0.5) + 1);
  }
  /**
   * BM25 term score:
   * IDF(t) * (tf * (k1 + 1)) / (tf + k1 * (1 - b + b * dl / avgdl))
   */
  computeTermScore(tf, idf, dl, avgdl) {
    const numerator = tf * (this.k1 + 1);
    const denominator = tf + this.k1 * (1 - this.b + this.b * dl / avgdl);
    return idf * (numerator / denominator);
  }
};

// src/scoring/JaccardScorer.ts
var JaccardScorer = class {
  constructor(uuidIndex) {
    this.uuidIndex = uuidIndex;
  }
  /**
   * Score all documents by tag overlap with source tags.
   * J(A,B) = |A intersection B| / |A union B|
   */
  scoreByTags(sourceTags) {
    const scores = /* @__PURE__ */ new Map();
    if (sourceTags.length === 0) return scores;
    const sourceSet = new Set(sourceTags);
    for (const [uuid, entry] of Object.entries(this.uuidIndex)) {
      if (entry.tags.length === 0) continue;
      const targetSet = new Set(entry.tags);
      const score = this.jaccard(sourceSet, targetSet);
      if (score > 0) {
        scores.set(uuid, score);
      }
    }
    return scores;
  }
  /**
   * Score all documents by term set overlap (vocabulary overlap).
   * This ignores frequency -- just measures what % of unique terms are shared.
   */
  scoreByTermOverlap(sourceTerms, documentTerms) {
    const scores = /* @__PURE__ */ new Map();
    if (sourceTerms.size === 0) return scores;
    for (const [uuid, targetTerms] of documentTerms) {
      const score = this.jaccard(sourceTerms, targetTerms);
      if (score > 0) {
        scores.set(uuid, score);
      }
    }
    return scores;
  }
  /**
   * Compute Jaccard similarity between two sets.
   */
  jaccard(setA, setB) {
    let intersectionSize = 0;
    const [smaller, larger] = setA.size <= setB.size ? [setA, setB] : [setB, setA];
    for (const item of smaller) {
      if (larger.has(item)) intersectionSize++;
    }
    const unionSize = setA.size + setB.size - intersectionSize;
    if (unionSize === 0) return 0;
    return intersectionSize / unionSize;
  }
};

// src/scoring/CombinedScorer.ts
var CombinedScorer = class {
  constructor(app, settings, indexes) {
    this.app = app;
    this.settings = settings;
    this.indexes = indexes;
  }
  /**
   * Find related notes for a given source (text query or UUID).
   * Returns scored results sorted by combined score descending.
   */
  async findRelated(source, limit) {
    var _a, _b, _c, _d;
    const maxResults = limit != null ? limit : this.settings.maxRelatedNotes;
    const weights = this.settings.scoringWeights;
    const uuidIndex = this.indexes.getUuidIndex();
    const termIndex = this.indexes.getTermIndex();
    const documentStats = this.indexes.getDocumentStats();
    const corpusStats = this.indexes.getCorpusStats();
    const relationGraph = this.indexes.getRelationGraph();
    let queryTerms;
    let sourceTags = [];
    let sourceUuid = null;
    if (source.type === "text") {
      queryTerms = tokenize(source.query);
    } else {
      sourceUuid = source.uuid;
      const entry = uuidIndex[sourceUuid];
      if (!entry) return [];
      const file = this.app.vault.getAbstractFileByPath(entry.path);
      if (!file || !(file instanceof import_obsidian4.TFile)) return [];
      const content = await this.app.vault.cachedRead(file);
      const body = extractBodyText(content);
      queryTerms = tokenize(body);
      sourceTags = entry.tags;
    }
    if (queryTerms.length === 0 && sourceTags.length === 0 && !sourceUuid) {
      return [];
    }
    const bm25Scorer = new BM25Scorer(termIndex, documentStats, corpusStats);
    const bm25Scores = queryTerms.length > 0 ? bm25Scorer.score(queryTerms) : /* @__PURE__ */ new Map();
    const jaccardScorer = new JaccardScorer(uuidIndex);
    const jaccardScores = sourceTags.length > 0 ? jaccardScorer.scoreByTags(sourceTags) : /* @__PURE__ */ new Map();
    const sourceTermSet = new Set(queryTerms);
    const documentTermSets = this.buildDocumentTermSets(termIndex);
    const termOverlapScores = sourceTermSet.size > 0 ? jaccardScorer.scoreByTermOverlap(sourceTermSet, documentTermSets) : /* @__PURE__ */ new Map();
    const graphScores = /* @__PURE__ */ new Map();
    if (sourceUuid && relationGraph) {
      const visited = /* @__PURE__ */ new Set();
      visited.add(sourceUuid);
      const queue = [{ uuid: sourceUuid, dist: 0 }];
      while (queue.length > 0) {
        const current = queue.shift();
        if (current.dist >= 3) continue;
        const edges = relationGraph[current.uuid];
        if (!edges) continue;
        for (const edge of edges) {
          if (!visited.has(edge.target)) {
            visited.add(edge.target);
            const dist = current.dist + 1;
            graphScores.set(edge.target, 1 / (dist + 1));
            queue.push({ uuid: edge.target, dist });
          }
        }
      }
    }
    const normBm25 = this.normalizeScores(bm25Scores);
    const normJaccard = this.normalizeScores(jaccardScores);
    const normTermOverlap = this.normalizeScores(termOverlapScores);
    const normGraph = this.normalizeScores(graphScores);
    const allUuids = /* @__PURE__ */ new Set();
    for (const uuid of normBm25.keys()) allUuids.add(uuid);
    for (const uuid of normJaccard.keys()) allUuids.add(uuid);
    for (const uuid of normTermOverlap.keys()) allUuids.add(uuid);
    for (const uuid of normGraph.keys()) allUuids.add(uuid);
    if (sourceUuid) allUuids.delete(sourceUuid);
    const results = [];
    for (const uuid of allUuids) {
      const entry = uuidIndex[uuid];
      if (!entry) continue;
      const scores = {
        bm25: (_a = normBm25.get(uuid)) != null ? _a : 0,
        jaccard: (_b = normJaccard.get(uuid)) != null ? _b : 0,
        termOverlap: (_c = normTermOverlap.get(uuid)) != null ? _c : 0,
        graphProximity: (_d = normGraph.get(uuid)) != null ? _d : 0
      };
      const combinedScore = weights.bm25 * scores.bm25 + weights.jaccard * scores.jaccard + weights.termOverlap * scores.termOverlap + weights.graphProximity * scores.graphProximity;
      if (combinedScore < this.settings.minSimilarityThreshold) continue;
      results.push({
        uuid,
        scores,
        combinedScore,
        path: entry.path,
        title: entry.title
      });
    }
    results.sort((a, b) => b.combinedScore - a.combinedScore);
    return results.slice(0, maxResults);
  }
  /**
   * Min-max normalize a set of scores to [0, 1].
   * If all scores are equal (or empty), returns 0 for all.
   */
  normalizeScores(scores) {
    if (scores.size === 0) return scores;
    let min = Infinity;
    let max = -Infinity;
    for (const score of scores.values()) {
      if (score < min) min = score;
      if (score > max) max = score;
    }
    const range = max - min;
    if (range === 0) {
      const normalized2 = /* @__PURE__ */ new Map();
      for (const [uuid, score] of scores) {
        normalized2.set(uuid, score > 0 ? 0.5 : 0);
      }
      return normalized2;
    }
    const normalized = /* @__PURE__ */ new Map();
    for (const [uuid, score] of scores) {
      normalized.set(uuid, (score - min) / range);
    }
    return normalized;
  }
  /**
   * Build per-document term sets from the term index.
   * Used for term overlap (Jaccard on vocabulary).
   */
  buildDocumentTermSets(termIndex) {
    const docTerms = /* @__PURE__ */ new Map();
    for (const [term, postings] of Object.entries(termIndex)) {
      if (!postings) continue;
      for (const posting of postings) {
        let termSet = docTerms.get(posting.uuid);
        if (!termSet) {
          termSet = /* @__PURE__ */ new Set();
          docTerms.set(posting.uuid, termSet);
        }
        termSet.add(term);
      }
    }
    return docTerms;
  }
};

// src/views/RelatedNotesView.ts
var import_obsidian5 = require("obsidian");
var VIEW_TYPE_RELATED = "smart-relations-related";
var RelatedNotesView = class extends import_obsidian5.ItemView {
  constructor(leaf) {
    super(leaf);
    this.results = [];
    this.getRelatedForFile = null;
  }
  getViewType() {
    return VIEW_TYPE_RELATED;
  }
  getDisplayText() {
    return "Related Notes";
  }
  getIcon() {
    return "network";
  }
  /**
   * Set the callback function that retrieves related notes.
   * Called by the plugin after view creation.
   */
  setRelatedCallback(fn) {
    this.getRelatedForFile = fn;
  }
  async onOpen() {
    this.renderEmptyState("Open a note to see related notes");
  }
  async onClose() {
    this.contentEl.empty();
  }
  /**
   * Update the panel for the currently active file.
   */
  async updateForActiveFile() {
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      this.renderEmptyState("Open a markdown note to see related notes");
      return;
    }
    if (!this.getRelatedForFile) {
      this.renderEmptyState('Index not ready \u2014 run "Reindex vault" first');
      return;
    }
    this.contentEl.empty();
    const loading = this.contentEl.createEl("div", { cls: "sr-loading" });
    loading.setText("Finding related notes...");
    try {
      this.results = await this.getRelatedForFile(file);
      this.renderResults();
    } catch (e) {
      console.error("Smart Relations: Error finding related notes:", e);
      this.renderEmptyState("Error finding related notes");
    }
  }
  renderResults() {
    this.contentEl.empty();
    const container = this.contentEl.createEl("div", { cls: "smart-relations-container" });
    const header = container.createEl("div", { cls: "sr-header" });
    header.createEl("h4", { text: "Related Notes" });
    const refreshBtn = header.createEl("button", { cls: "sr-refresh-btn", attr: { "aria-label": "Refresh" } });
    refreshBtn.setText("\u21BB");
    refreshBtn.addEventListener("click", () => {
      void this.updateForActiveFile();
    });
    if (this.results.length === 0) {
      container.createEl("div", { cls: "sr-empty-state", text: "No related notes found" });
      return;
    }
    const list = container.createEl("div", { cls: "sr-results-list" });
    for (const result of this.results) {
      const item = list.createEl("div", { cls: "sr-result-item" });
      const titleRow = item.createEl("div", { cls: "sr-result-title-row" });
      const titleEl = titleRow.createEl("a", {
        cls: "sr-result-title",
        text: result.title
      });
      titleEl.addEventListener("click", (e) => {
        e.preventDefault();
        void this.app.workspace.openLinkText(result.path, "");
      });
      const scoreClass = result.combinedScore >= 0.7 ? "sr-score-high" : result.combinedScore >= 0.4 ? "sr-score-mid" : "sr-score-low";
      titleRow.createEl("span", {
        cls: `sr-result-score ${scoreClass}`,
        text: result.combinedScore.toFixed(2)
      });
      const details = item.createEl("details", { cls: "sr-result-breakdown" });
      details.createEl("summary", { text: "Score breakdown" });
      const breakdownList = details.createEl("div", { cls: "sr-breakdown-list" });
      const scoreLabels = [
        { key: "bm25", label: "BM25" },
        { key: "jaccard", label: "Tag similarity" },
        { key: "termOverlap", label: "Term overlap" },
        { key: "graphProximity", label: "Graph proximity" }
      ];
      for (const { key, label } of scoreLabels) {
        const row = breakdownList.createEl("div", { cls: "sr-score-row" });
        row.createEl("span", { cls: "sr-score-label", text: label });
        row.createEl("span", { cls: "sr-score-value", text: result.scores[key].toFixed(3) });
      }
    }
  }
  renderEmptyState(message) {
    this.contentEl.empty();
    const container = this.contentEl.createEl("div", { cls: "smart-relations-container" });
    container.createEl("div", { cls: "sr-empty-state", text: message });
  }
};

// src/views/SuggestionModal.ts
var import_obsidian6 = require("obsidian");
var RelationSuggestionModal = class extends import_obsidian6.FuzzySuggestModal {
  constructor(app, results, onChoose) {
    super(app);
    this.results = results;
    this.onChooseResult = onChoose;
    this.setPlaceholder("Select a note to add as related...");
  }
  getItems() {
    return this.results;
  }
  getItemText(item) {
    return `${item.title} (${item.combinedScore.toFixed(3)})`;
  }
  onChooseItem(item, _evt) {
    this.onChooseResult(item);
  }
};

// src/main.ts
var SmartRelationsPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.statusBarEl = null;
  }
  async onload() {
    await this.loadSettings();
    const cache = new IndexCache(this);
    this.indexManager = new IndexManager(this.app, this.settings, cache);
    this.scorer = new CombinedScorer(this.app, this.settings, this.indexManager);
    this.registerView(VIEW_TYPE_RELATED, (leaf) => {
      const view = new RelatedNotesView(leaf);
      view.setRelatedCallback(async (file) => {
        const uuid = this.indexManager.getUuidForFile(file);
        if (!uuid) return [];
        return this.scorer.findRelated({ type: "uuid", uuid });
      });
      return view;
    });
    const loaded = await this.indexManager.loadAllIndexes();
    if (!loaded) {
      this.app.workspace.onLayoutReady(() => {
        void (async () => {
          new import_obsidian7.Notice("Smart Relations: Building index for the first time...");
          await this.indexManager.rebuildAll((msg) => {
            this.updateStatusBar(msg);
          });
          this.updateStatusBarDefault();
          this.refreshRelatedPanel();
        })();
      });
    } else {
      this.updateStatusBarDefault();
    }
    this.registerEvent(this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian7.TFile && file.extension === "md") {
        this.indexManager.handleFileChange(file, "create");
      }
    }));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (file instanceof import_obsidian7.TFile && file.extension === "md") {
        this.indexManager.handleFileChange(file, "modify");
      }
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      if (file instanceof import_obsidian7.TFile && file.extension === "md") {
        this.indexManager.handleFileChange(file, "delete");
      }
    }));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      if (file instanceof import_obsidian7.TFile && file.extension === "md") {
        this.indexManager.handleFileRename(file, oldPath);
      }
    }));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
      this.refreshRelatedPanel();
    }));
    this.addRibbonIcon("network", "Reindex vault", () => {
      void this.reindexVault();
    });
    this.addCommand({
      id: "reindex-vault",
      name: "Reindex vault",
      callback: () => {
        void this.reindexVault();
      }
    });
    this.addCommand({
      id: "find-related-notes",
      name: "Find related notes",
      callback: () => {
        void this.activateRelatedPanel();
      }
    });
    this.addCommand({
      id: "show-relation-graph",
      name: "Show relation graph",
      callback: () => {
        new import_obsidian7.Notice("Graph view coming in a future update");
      }
    });
    this.addCommand({
      id: "suggest-relations",
      name: "Suggest relations for current note",
      callback: () => {
        void this.suggestRelations();
      }
    });
    this.addSettingTab(new SmartRelationsSettingTab(this.app, this));
    this.statusBarEl = this.addStatusBarItem();
    this.updateStatusBarDefault();
  }
  onunload() {
    console.log("Smart Relations: unloading plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateStatusBar(message) {
    if (this.statusBarEl) {
      this.statusBarEl.setText(`SR: ${message}`);
    }
  }
  updateStatusBarDefault() {
    if (!this.indexManager.isLoaded()) {
      this.updateStatusBar("Not indexed");
      return;
    }
    const count = this.indexManager.getNoteCount();
    const lastTime = this.indexManager.getLastIndexTime();
    const timeStr = lastTime ? this.formatRelativeTime(lastTime) : "never";
    this.updateStatusBar(`${count} notes | ${timeStr}`);
  }
  formatRelativeTime(timestamp) {
    const diff = Date.now() - timestamp;
    const seconds = Math.floor(diff / 1e3);
    if (seconds < 60) return "just now";
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    return `${Math.floor(hours / 24)}d ago`;
  }
  async reindexVault() {
    new import_obsidian7.Notice("Smart Relations: Reindexing vault...");
    await this.indexManager.rebuildAll((msg) => {
      this.updateStatusBar(msg);
    });
    this.updateStatusBarDefault();
    this.refreshRelatedPanel();
    new import_obsidian7.Notice("Smart Relations: Reindex complete!");
  }
  async activateRelatedPanel() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_RELATED);
    if (leaves.length > 0) {
      this.app.workspace.revealLeaf(leaves[0]);
    } else {
      const leaf = this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_RELATED, active: true });
        this.app.workspace.revealLeaf(leaf);
      }
    }
    this.refreshRelatedPanel();
  }
  refreshRelatedPanel() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_RELATED);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof RelatedNotesView) {
        void view.updateForActiveFile();
      }
    }
  }
  async suggestRelations() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian7.Notice("No active file");
      return;
    }
    if (!this.indexManager.isLoaded()) {
      new import_obsidian7.Notice('Index not ready \u2014 run "Reindex vault" first');
      return;
    }
    const uuid = this.indexManager.getUuidForFile(file);
    if (!uuid) {
      new import_obsidian7.Notice("Current note has no UUID in frontmatter");
      return;
    }
    const results = await this.scorer.findRelated({ type: "uuid", uuid });
    if (results.length === 0) {
      new import_obsidian7.Notice("No related notes found");
      return;
    }
    new RelationSuggestionModal(this.app, results, (selected) => {
      void this.app.fileManager.processFrontMatter(file, (fm) => {
        if (!fm["related"]) {
          fm["related"] = [];
        }
        const related = fm["related"];
        const existing = related.some((entry) => {
          if (typeof entry === "string") return entry === selected.uuid;
          if (typeof entry === "object" && entry !== null && "uuid" in entry) {
            return entry.uuid === selected.uuid;
          }
          return false;
        });
        if (existing) {
          new import_obsidian7.Notice(`"${selected.title}" is already in related`);
          return;
        }
        if (this.settings.useRichRelatedFormat) {
          related.push({ uuid: selected.uuid, rel: "related", auto: true });
        } else {
          related.push(selected.uuid);
        }
        new import_obsidian7.Notice(`Added "${selected.title}" to related`);
      });
    }).open();
  }
};
